#   ________   ________   ________   ___  __     ________
#  |\   __  \ |\   __  \ |\   ____\ |\  \|\  \  |\   ____\
#  \ \  \|\  \\ \  \|\  \\ \  \___| \ \  \/  /|_\ \  \___|_
#   \ \   ____\\ \   __  \\ \  \     \ \   ___  \\ \_____  \
#    \ \  \___| \ \  \ \  \\ \  \____ \ \  \\ \  \\|____|\  \
#     \ \__\     \ \__\ \__\\ \_______\\ \__\\ \__\ ____\_\  \
#      \|__|      \|__|\|__| \|_______| \|__| \|__||\_________\
#                                                  \|_________|
#                            By: Hempfest
#                                 Version: ?.?.?
pack-size: 27
pack-name: '&e&o{PLAYER}''s &fBackpack.'
pack-lore:
  - '&ePack creation : [&7{DATE}&e]'
  - '&2Size&f: &73 Row'
  - '&6ID&f: &6{&e{RANDOM_ID_SHORT}&6}'